# ----
# Site

title: Justin Slack
subtitle: Personal website
url: ""
baseurl: ""

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Justin Slack personal web site
author:
  name: Justin Slack
  email: justin@justin.com

# -----
# Build

# include: ["_pages", "_headers", "_redirects"]

include: ["_pages", "_redirects"]

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

sass:
  style: compressed
  sourcemap: true

collections:
  articles:
    title: articles

    permalink: /:collection/:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# Custom headers
# webrick:
#   headers:
#     Content-Security-Policy: default-src 'self'; object-src 'none'; img-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' https://d33wubrfki0l68.cloudfront.net; manifest-src 'self'; connect-src 'self'; worker-src 'self'

